contract_analyst_task:
  description: >
    Analyze the provided contract PDF and extract the following specific fields.
    Use the PDFSearchTool to search through the contract document at {contract_path}.
    For each field, use the tool to find the most relevant section and extract the information.

    1. Save the extracted data:
       - Use the FileWriterTool to save the JSON data
         Save as 'output/{contract_name}_extracted_contract_details.json'
       
       2. Create Excel file:
          - Use the ExcelWriterTool to create a formatted Excel file
          - Save as 'output/{contract_name}_extracted_contract_details.xlsx'
          - Include columns: Contract Section, Field Name, Value
          - Apply proper formatting and column widths

    Fields to extract:
    Contract Basics:
    - Contract Title
    - Contract Reference Number
    - Contract Type
    - Effective Date
    - Expiration Date
    - Contract Status

    Parties Information:
    - Client Company Name
    - Client Address
    - Vendor Company Name
    - Vendor Address
    - Primary Contact (Client)
    - Primary Contact (Vendor)

    Financial Terms:
    - Total Contract Value
    - Payment Schedule
    - Payment Terms
    - Currency
    - Payment Method

    Terms & Termination:
    - Termination Clause (including notice period and allowed reasons)
    - Renewal Terms (manual/auto-renewal and cancellation requirements)
    - Notice Period for Termination
    - Notice Period for Non-Renewal
    - Contract Duration (must align with start/end dates)

  expected_output: >
    Contract details saved in multiple formats:
    - JSON file for structured data
    - Excel file with proper formatting and layout
    Each field should be populated with either the extracted value or marked as 
    "Not Specified" if not found in the contract.
  agent: contract_analyst

contract_validator_task:
  description: >
    Review the extracted contract data and validate:
    - Verify all required fields are present and properly formatted
    - Check date formats and validity
    - Validate monetary values and payment terms
    - Ensure contact information is complete
    - Flag any missing critical fields
    - Verify termination and renewal terms are clearly specified
    - Confirm contract duration matches start/end dates
  expected_output: >
    A validation report containing:
    - List of missing required fields
    - List of identified risks
    - Overall validation status (is_valid flag)
    - Recommendations for resolution
  agent: contract_validator
  context:
    - contract_analyst_task

notification_specialist_task:
  description: >
    Create a clear, concise summary of the contract analysis including:
    - Key contract details (title, parties, value, dates)
    - Important terms (termination, renewal, notice periods)
    - Validation results and any concerns
    - Missing critical information
    - Required actions from stakeholders
    Make it suitable for business stakeholders to review.
  expected_output: >
    A well-formatted email summary in plain text, highlighting the most important
    aspects and any items requiring attention.
  agent: notification_specialist
  context:
    - contract_validator_task
