contract_analyst_task:
  description: >
    Analyze the provided contract PDF and extract the following specific fields.
    Use the PDFSearchTool to search through the contract document at {contract_path}.
    For each field, use the tool to find the most relevant section and extract the information.

    1. Save the extracted data:
       - Use the FileWriterTool to save the JSON data
         Save as 'output/{contract_name}_extracted_contract_details.json'
       
       2. Create Excel file:
          - Use the ExcelWriterTool to create a formatted Excel file
          - Save as 'output/{contract_name}_extracted_contract_details.xlsx'
          - Include columns: Contract Section, Field Name, Value
          - Apply proper formatting and column widths

    Fields to extract:
    Contract Basics:
    - Contract Title
    - Contract Reference Number
    - Contract Type
    - Effective Date
    - Expiration Date
    - Contract Status

    Parties Information:
    - Client Company Name
    - Client Address
    - Vendor Company Name
    - Vendor Address
    - Primary Contact (Client)
    - Primary Contact (Vendor)

    Financial Terms:
    - Total Contract Value
    - Payment Schedule
    - Payment Terms
    - Currency
    - Payment Method

    Terms & Termination:
    - Termination Clause (including notice period and allowed reasons)
    - Renewal Terms (manual/auto-renewal and cancellation requirements)
    - Notice Period for Termination
    - Notice Period for Non-Renewal
    - Contract Duration (must align with start/end dates)

  expected_output: >
    Contract details saved in multiple formats:
    - JSON file for structured data
    - Excel file with proper formatting and layout
    Each field should be populated with either the extracted value or marked as 
    "Not Specified" if not found in the contract.
  agent: contract_analyst

contract_validator_task:
  description: >
    Review the extracted contract data from output/{contract_name}_extracted_contract_details.json
    and perform a thorough validation:

    1. First read and parse the extracted data file:
       - Read the JSON file from the output directory
       - Parse all sections: Contract Basics, Parties Information, etc.
       - Compare against the required fields list
       
    2. Check for Missing Fields:
       - Compare each field in the JSON against required fields
       - Only mark as missing if field is empty or "Not Specified"
       - Group any missing fields by category
       
    3. Identify Risk Patterns:
       - Auto-renewal clauses in Renewal Terms
       - Vague or missing termination language
       - Notice periods less than 30 days
       - Undefined/unclear payment terms
       
    4. Generate Recommendations:
       - Specific actions for any truly missing fields
       - Risk mitigation suggestions
       - Compliance improvements

    5. Create Validation Report:
       Use FileWriterTool to save a structured JSON report as 'output/{contract_name}_validation_report.json'
       that includes:
       - is_valid: true if all required fields have values and no risks found
       - missing_fields: array of fields that are empty or "Not Specified"
       - risk_flags: array of identified risks
       - recommendations: array of specific recommendations

    Required Fields by Category:
    Contract Basics:
    - Contract Title
    - Contract Reference Number
    - Contract Type
    - Effective Date
    - Expiration Date
    - Contract Status

    Parties Information:
    - Client Company Name
    - Client Address
    - Vendor Company Name
    - Vendor Address
    - Primary Contact (Client)
    - Primary Contact (Vendor)

    Financial Terms:
    - Total Contract Value
    - Payment Schedule
    - Payment Terms
    - Currency
    - Payment Method

    Terms & Termination:
    - Termination Clause
    - Renewal Terms
    - Notice Period for Termination
    - Notice Period for Non-Renewal
    - Contract Duration

  expected_output: >
    A structured JSON validation report containing:
    - Overall validity status (is_valid)
    - List of any missing required fields
    - List of identified risk flags
    - Specific recommendations for resolution
    The report must be machine-readable and properly formatted.
  agent: contract_validator
  context:
    - contract_analyst_task

notification_specialist_task:
  description: >
    Create a professional email summary of the contract analysis using data from:
    - Contract details: output/{contract_name}_extracted_contract_details.json
    - Validation results: output/{contract_name}_validation_report.json

    Save the summary as 'output/{contract_name}_email_summary.txt'

    Format the summary as follows:

    CONTRACT SUMMARY: [Contract Title]

    Vendor: [Vendor Name]
    Client: [Client Name]
    Start Date: [Effective Date]
    End Date: [Expiration Date]
    Total Contract Value: [Value with Currency]

    Status: [Complete status message based on validation]

    ---

    [If missing fields exist:]
    MISSING FIELDS:
    - [List each missing field]

    [If risks exist:]
    IDENTIFIED RISKS:
    - [List each risk flag]

    [If recommendations exist:]
    RECOMMENDATIONS:
    - [List each recommendation]

    ---

    Generated by Contract Processing AI Assistant

    Notes:
    - Only include sections that have content
    - Use clear business language
    - Format with proper spacing and bullet points
    - Status should be either:
      "This contract appears complete and compliant."
      or
      "This contract requires attention due to missing information or risks."

  expected_output: >
    A professionally formatted email summary in plain text (.txt), highlighting key
    contract details, any issues found, and specific recommendations. The summary
    should be immediately actionable by business stakeholders.
  agent: notification_specialist
  context:
    - contract_validator_task
