contract_analyst_task:
  description: >
    Analyze the provided contract PDF and extract the following specific fields.
    Use the PDFSearchTool to search through the contract document at {contract_path}.
    For each field, use the tool to find the most relevant section and extract the information.

    1. Save the extracted data using FileWriterTool with these required fields:

    Contract Basics section:
    - Contract Title
    - Contract Reference Number
    - Contract Type
    - Effective Date
    - Expiration Date
    - Contract Status

    Parties Information section:
    - Client Company Name
    - Client Address
    - Vendor Company Name
    - Vendor Address
    - Primary Contact (Client)
    - Primary Contact (Vendor)

    Financial Terms section:
    - Total Contract Value
    - Payment Schedule
    - Payment Terms
    - Currency
    - Payment Method

    Terms & Termination section:
    - Termination Clause
    - Renewal Terms
    - Notice Period for Termination
    - Notice Period for Non-Renewal
    - Contract Duration

    Important Rules:
    - Save as valid JSON with these exact section and field names
    - Use "Not Specified" for missing information
    - Write ONLY the JSON data to the file
    - No explanatory text or metadata in the output file

    2. Create Excel file using ExcelWriterTool:
       - Create a new Excel file with proper formatting
       - Include columns: Contract Section, Field Name, Value
       - Apply proper column widths and formatting
       - Match the JSON structure exactly
       - Save as output/{contract_name}/{contract_name}_extracted_contract_details.xlsx

    Save outputs as:
    - JSON: output/{contract_name}/{contract_name}_extracted_contract_details.json
    - Excel: output/{contract_name}/{contract_name}_extracted_contract_details.xlsx

  expected_output: >
    output/{contract_name}/{contract_name}_extracted_contract_details.json:
    Raw JSON data containing all contract fields organized in sections.

    output/{contract_name}/{contract_name}_extracted_contract_details.xlsx:
    Excel spreadsheet with contract data in tabular format.

  agent: contract_analyst

contract_validator_task:
  description: >
    Review the extracted contract data and perform validation:

    1. First read the contract details using FileReaderTool:
       Read and parse: output/{contract_name}/{contract_name}_extracted_contract_details.json
       
    2. Check for Missing Fields:
       - Compare each field in the JSON against required fields
       - Only mark as missing if field is empty or "Not Specified"
       - Group any missing fields by category
       
    3. Identify Risk Patterns:
       - Auto-Renewal Risk Assessment:
         * Check if Renewal Terms contains "auto" or "automatic" renewal language
         * If auto-renewal exists, verify Notice Period for Non-Renewal
         * Flag as risk if:
           - Notice period is missing/not specified
           - Notice period is less than 30 days
           - Notice period format is unclear
       - Termination Risk Assessment:
         * Check for vague or missing termination language
         * Verify notice periods are clearly specified
         * Flag if notice period is less than 30 days
       - Payment Terms Risk Assessment:
         * Check for undefined/unclear payment terms
         * Verify payment schedule and method are specified
         * Flag any ambiguous financial terms
       
    4. Generate Recommendations:
       - For auto-renewal risks:
         * Suggest extending notice period to minimum 30 days
         * Recommend clarifying renewal process
         * Propose manual renewal if notice period can't be extended
       - For other identified risks:
         * Specific actions for missing fields
         * Risk mitigation suggestions
         * Compliance improvements

    5. Create Validation Report:
       Use FileWriterTool to write the validation results in JSON format.
       The JSON must contain four fields:
       - is_valid: true or false
       - missing_fields: an array of any fields marked "Not Specified"
       - risk_flags: an array of risk descriptions
       - recommendations: an array of mitigation steps

       The output must be valid JSON and should not include any additional explanation or metadata.
       Important:
       - Write ONLY the raw JSON data
       - No explanatory text or metadata
       - No file paths or success messages

       Save validation report as:
       output/{contract_name}/{contract_name}_validation_report.json

  expected_output: >
    output/{contract_name}/{contract_name}_validation_report.json:
    Raw JSON data containing validation results with no metadata or explanatory text.

  agent: contract_validator
  context:
    - contract_analyst_task

notification_specialist_task:
  description: >
    Create a professional email summary using data from two sources:

    1. Read contract details using FileReaderTool:
       output/{contract_name}/{contract_name}_extracted_contract_details.json

    2. Read validation results using FileReaderTool:
       output/{contract_name}/{contract_name}_validation_report.json

    3. Create summary using this exact format:
    CONTRACT SUMMARY: [Contract Title from contract details]
    Vendor: [Vendor Company Name from contract details]
    Client: [Client Company Name from contract details]
    Start Date: [Effective Date from contract details]
    End Date: [Expiration Date from contract details]
    Total Contract Value: [Total Contract Value from contract details]
    Status: [Based on is_valid from validation report]
    ---
    [Include these sections only if present in validation report:]

    MISSING FIELDS:
    - [Each field from missing_fields array]

    IDENTIFIED RISKS:
    - [Each risk from risk_flags array]

    RECOMMENDATIONS:
    - [Each item from recommendations array]
    ---
    Generated by Contract Processing AI Assistant

    Important Rules:
    - Use actual values from JSON files, not placeholders
    - Follow exact spacing shown above
    - Include sections only if they have content
    - Status must be exactly one of:
      "This contract appears complete and compliant."
      "This contract requires attention due to missing information or risks."
    - No metadata or file paths in the output
    - No explanatory text or casual language

    Save ONLY the formatted summary text as:
    output/{contract_name}/{contract_name}_email_summary.txt

  expected_output: >
    output/{contract_name}/{contract_name}_email_summary.txt:
    Plain text email summary with no metadata or file path information.

  agent: notification_specialist
  context:
    - contract_validator_task
